# .github/workflows/run_g_force.yml
name: Simulação de Viabilidade da Cápsula
# Define quando este workflow deve rodar:
on:
  push:
    # Rodar em qualquer commit na branch 'main'
    branches: [ main ] 
  workflow_dispatch:

jobs:
  run-simulations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4
      
    # PASSO DE DIAGNÓSTICO: Mostra os arquivos que o Action "vê"
    # O objetivo é verificar se a pasta 'Simulations' está com letra maiúscula ou minúscula
    - name: Listar o diretório de trabalho
      run: ls -R
      
    - name: Configurar Ambiente Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' 

    # IMPORTANTE: Verifique se 'Simulations' está com a letra maiúscula correta
    - name: Executar Simulação de Força G
      run: python Simulations/g_force_calculator.py
      
    - name: Executar Simulação de Radiação
      run: python Simulations/radiation_shield.py
      
    - name: Executar Simulação Térmica
      run: python Simulations/thermal_simulator.py
      
