# .github/workflows/run_g_force.yml

name: Simulação de Viabilidade da Cápsula

# Define quando este workflow deve rodar:
on:
  push:
    # Rodar em qualquer commit na branch 'main'
    branches: [ main ] 
  workflow_dispatch:

jobs:
  run-simulations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Ambiente Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' 

    # 1. Executa o script de cálculo de G-Force na nova pasta
    - name: Executar Simulação de Força G
      run: python Simulations/g_force_calculator.py
      
    # 2. Executa a Simulação de Radiação na nova pasta
    - name: Executar Simulação de Radiação
      run: python Simulations/radiation_shield.py
      
    # 3. Executa a Simulação Térmica na nova pasta
    - name: Executar Simulação Térmica
      run: python Simulations/thermal_simulator.py
