# .github/workflows/run_g_force.yml

name: Simulação de Viabilidade da Cápsula

# Define quando este workflow deve rodar:
on:
  push:
    # Rodar AGORA em qualquer commit na branch 'main'
    branches: [ main ] 
  # Permite rodar manualmente na aba 'Actions'
  workflow_dispatch:

jobs:
  run-simulations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Ambiente Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' 

    - name: Executar Simulação de Força G
      run: python g_force_calculator.py
      
    - name: Executar Simulação de Radiação
      run: python radiation_shield.py
      
    - name: Executar Simulação Térmica
      run: python thermal_simulator.py
