# .github/workflows/run_g_force.yml

name: Calcular G-Force

# Define quando este workflow deve rodar:
on:
  push:
    # Rodar sempre que houver um commit na branch 'main' (que você renomeou)
    branches: [ main ] 
    # Opcional: Rodar apenas quando o script de cálculo for modificado
    paths:
      - 'g_force_calculator.py'
  # Permite rodar manualmente na aba 'Actions'
  workflow_dispatch:

jobs:
  run-g-force-calc:
    # O tipo de máquina virtual que o GitHub usará para rodar o job
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do código: Pega o seu código do repositório
    - name: Checkout do Código
      uses: actions/checkout@v4

    # 2. Configura o Python na máquina virtual
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' 

    # 3. Executa o script de cálculo de G-Force
    - name: Executar Cálculo de G-Force e exibir resultados
      run: python g_force_calculator.py
